language: cpp
os: linux
dist: bionic

branches:
    only:
        - master

jobs:
    include:
        - compiler: gcc
          before_install:
              - sudo apt-get install xorg-dev
              - sudo apt-get install mesa-utils libgl1-mesa-dev
        - compiler: clang
          before_install:
              - sudo apt-get install xorg-dev
              - sudo apt-get install mesa-utils libgl1-mesa-dev

script:
    - mkdir build && cd build
    - cmake .. -G "Unix Makefiles" -DATLAS_BUILD_EXAMPLES=OFF -DATLAS_BUILD_GL_TEST=OFF -DATLAS_BUILD_GUI_TEST=OFF -DGLFW_BUILD_DOCS=OFF -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_INSTALL=OFF -DGLM_TEST_ENABLE=OFF -DBUILD_SHARED_LIBS=OFF
    - make
    - make test

