language:
    - cpp

matrix:
    include:
        - os: linux
          dist: bionic
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - g++-9.1
          env:
              - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
before_install:
    - eval "${MATRIX_EVAL}"

script:
    - mkdir build && cd build
    - cmake .. -G "Unix Makefiles" -DATLAS_BUILD_EXAMPLES=OFF -DATLAS_BUILD_GL_TEST=OFF -DATLAS_BUILD_GUI_TEST=OFF -DGLFW_BUILD_DOCS=OFF -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_INSTALL=OFF -DGLM_TEST_ENABLE=OFF
    - cmake --build . --config Release
    - cmake --build . --target RUN_TESTS --config Release

