version: '3.0.0.{build}'

image: Visual Studio 2019

platform:
    - x64

configuration:
    - Release
    - Debug

before_build:
    - ps: New-Item -Path . -Name "build" -ItemType "directory"
    - ps: Set-Location -Path ./build
    - cmake -G "Visual Studio 16 2019" ..

build:
    project: $(APPVEYOR_BUILD_FOLDER)\$(APPVEYOR_PROJECT_NAME).sln

