name: GCC

on: [push]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Linux GCC Debug",
            artifact: "linux_gcc_debug.tar.xz",
            os: ubuntu-latest,
            build_type: "Debug",
            cc: "gcc-10",
            cxx: "g++-10"
          }
        - {
            name: "Linux GCC Release",
            artifact: "linux_gcc_release.tar.xz",
            os: ubuntu-latest,
            build_type: "Release",
            cc: "gcc-10",
            cxx: "g++-10"
          }
    steps:
      - uses: actions/checkout@v2

      - name: Install Packages
        shell: bash
        run: |
          sudo apt-get install xorg-dev mesa-utils libgl1-mesa-dev

      - name: Setup
        shell: bash
        env:
          BUILD_TYPE: ${{ matrix.config.build_type }}
          CC: ${{ matrix.config.cc }}
          CXX: ${{ matrix.config.cxx }}
        run: |
          cmake --preset=gcc -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_SHARED_LIBS=OFF
      - name: Build
        shell: bash
        working-directory: ./build
        env:
          CC: ${{ matrix.config.cc }}
          CXX: ${{ matrix.config.cxx }}
        run: |
          make
      - name: Test
        shell: bash
        working-directory: ./build
        env:
          CC: ${{ matrix.config.cc }}
          CXX: ${{ matrix.config.cxx }}
        run: |
          make test
